apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-web
  namespace: app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-web
  template:
    metadata:
      labels:
        app: hello-web
    spec:
      containers:
      - name: nginx
        image: nginx:1.27
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-web
  namespace: app-dev
spec:
  selector:
    app: hello-web
  ports:
  - port: 80
    targetPort: 80